/// Flutter icons RainyIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RainyIcon
///      fonts:
///       - asset: fonts/RainyIcon.ttf
///
/// 
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class RainyIcon {
  RainyIcon._();

  static const _kFontFam = 'RainyIcon';

  static const IconData hail = const IconData(0xe800, fontFamily: _kFontFam);
}
